import React from 'react';
import './PolicyStyles.css';

const PrivacyPolicy = () => (
  <div className="policy-container">
    <h1>Privacy Policy</h1>
    <p className="policy-date">Last updated: June 13, 2025</p>
    <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
    <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank" rel="noopener noreferrer">Privacy Policy Generator</a>.</p>
    <h2>Interpretation and Definitions</h2>
    <h3>Interpretation</h3>
    <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
    <h3>Definitions</h3>
    <p>For the purposes of this Privacy Policy:</p>
    <ul>
      <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
      <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
      <li><strong>Application</strong> refers to Vaya-sports, the software program provided by the Company.</li>
      <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to AURA EMANATING TEKNOLOGY, 3rd Floor, 306, Plot No. 11, LSC Pocket-B, Durga Complex Mayur Vihar Phase II,  Delhi - 110 091(INDIA.</li>
      <li><strong>Country</strong> refers to: Uttar Pradesh,  India</li>
      <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
      <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
      <li><strong>Service</strong> refers to the Application.</li>
      <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
      <li><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
      <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
      <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
    </ul>
    <h2>Collecting and Using Your Personal Data</h2>
    <h3>Types of Data Collected</h3>
    <h4>Personal Data</h4>
    <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
    <ul>
      <li>Email address</li>
      <li>First name and last name</li>
      <li>Phone number</li>
      <li>Address, State, Province, ZIP/Postal code, City</li>
      <li>Usage Data</li>
    </ul>
    <h4>Usage Data</h4>
    <p>Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's IP address, browser type, browser version, pages of our Service that You visit, time and date of Your visit, time spent on those pages, unique device identifiers and other diagnostic data.</p>
    <h4>Information from Third-Party Social Media Services</h4>
    <p>The Company allows You to create an account and log in to use the Service through various Third-party Social Media Services (Google, Facebook, Instagram, Twitter, LinkedIn). We may collect Personal data already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.</p>
    <p>You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, you are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.</p>
    <h4>Information Collected while Using the Application</h4>
    <p>While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:</p>
    <ul>
      <li>Information regarding your location</li>
      <li>Information from your Device's phone book (contacts list)</li>
    </ul>
    <p>We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device. You can enable or disable access to this information at any time, through Your Device settings.</p>
    <h3>Use of Your Personal Data</h3>
    <p>The Company may use Personal Data for the following purposes:</p>
    <ul>
      <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
      <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
      <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
      <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
      <li><strong>To provide You</strong> with news, special offers and general information about other goods, services and events which we offer.</li>
      <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
      <li><strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
    </ul>
    <h3>Retention of Your Personal Data</h3>
    <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>
    <h3>Transfer of Your Personal Data</h3>
    <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
    <h3>Delete Your Personal Data</h3>
    <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may update, amend, or delete your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.</p>
    <h3>Children's Privacy</h3>
    <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
    <h2>Links to Other Websites</h2>
    <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
  </div>
);

export default PrivacyPolicy;
